dist: xenial
services:
  - xvfb
addons:
  chrome: stable

language: java
jdk: openjdk8
before_script:
  - export DISPLAY=:99.0
  - sleep 3

script:
#  - xvfb-run --server-args="-screen 0 1024x768x24" make test
  - mvn clean test






